services:
  - type: web
    name: kollita-api
    runtime: image
    plan: free
    region: oregon
    image:
      owner: gabrieldaquino23-collab
      image: kollita-api
      tag: latest
    dockerCommand: dotnet KollitaApi.dll
    healthCheckPath: /health
    autoScaling:
      enabled: true
      minInstances: 1
      maxInstances: 2
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: DATABASE_URL
        sync: true
      - key: PORT
        value: "8080"
      - key: JWT_KEY
        generateValue: true
      - key: JWT_ISSUER
        value: "KollitaApi"
      - key: JWT_AUDIENCE
        value: "KollitaPro"

  - type: redis
    name: kollita-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: allkeys-lru
