-- ═══════════════════════════════════════════════
-- KOLLITA API — POSTGRESQL SCHEMA (Supabase)
-- ═══════════════════════════════════════════════

-- PEDIDOS
CREATE TABLE IF NOT EXISTS "Pedidos" (
    "Id" BIGINT PRIMARY KEY,
    "NumeroNota" VARCHAR(10) NOT NULL,
    "Secretario" VARCHAR(100) NOT NULL,
    "Cliente" VARCHAR(200) NOT NULL DEFAULT 'CONSUMIDOR FINAL',
    "Subtotal" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Descuento" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Total" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Fecha" VARCHAR(20) NOT NULL,
    "FechaID" VARCHAR(10) NOT NULL,
    "Hora" VARCHAR(20) NOT NULL,
    "MetodoPago" VARCHAR(20) NULL,
    "PorcentajeDescuento" NUMERIC(5,2) NOT NULL DEFAULT 0,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'PREPARADO',
    "EsDelivery" BOOLEAN NOT NULL DEFAULT FALSE,
    "MontoDelivery" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "RepartidorDelivery" VARCHAR(100) NULL,
    "TotalEntregado" NUMERIC(18,2) NULL,
    "SaldoCobrado" NUMERIC(18,2) NULL,
    "EfectivoPagado" NUMERIC(18,2) NULL,
    "QrPagado" NUMERIC(18,2) NULL,
    "FechaEntrega" VARCHAR(20) NULL,
    "HoraEntrega" VARCHAR(20) NULL,
    "FechaIDEntrega" VARCHAR(10) NULL,
    "SecretarioEntrega" VARCHAR(100) NULL,
    "EntregadoPor" VARCHAR(100) NULL,
    "TurnoEntrega" VARCHAR(50) NULL,
    "Anticipo" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "MetodoAnticipo" VARCHAR(20) NULL,
    "Origen" VARCHAR(20) NULL,
    "PedidoMovilId" BIGINT NULL,
    "NotaMovil" VARCHAR(500) NULL,
    "SucursalMovil" VARCHAR(100) NULL
);
CREATE INDEX IF NOT EXISTS "IX_Pedidos_FechaID" ON "Pedidos"("FechaID");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_Estado" ON "Pedidos"("Estado");
CREATE INDEX IF NOT EXISTS "IX_Pedidos_Secretario" ON "Pedidos"("Secretario");

-- ITEMS DE PEDIDO
CREATE TABLE IF NOT EXISTS "ItemsPedido" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PedidoId" BIGINT NOT NULL,
    "Nombre" VARCHAR(200) NOT NULL,
    "Cantidad" INT NOT NULL,
    "Precio" NUMERIC(18,2) NOT NULL,
    CONSTRAINT "FK_ItemsPedido_Pedidos" FOREIGN KEY ("PedidoId") REFERENCES "Pedidos"("Id") ON DELETE CASCADE
);

-- PENDIENTES (APP MÓVIL)
CREATE TABLE IF NOT EXISTS "Pendientes" (
    "Id" BIGINT PRIMARY KEY,
    "Client" VARCHAR(200) NOT NULL,
    "Branch" VARCHAR(100) NOT NULL,
    "BranchTel" VARCHAR(20) NULL,
    "Method" VARCHAR(20) NOT NULL,
    "Note" VARCHAR(500) NULL,
    "Subtotal" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Discount" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Total" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Time" VARCHAR(10) NOT NULL,
    "Date" VARCHAR(15) NOT NULL,
    "FechaISO" VARCHAR(10) NOT NULL,
    "Estado" VARCHAR(20) NOT NULL DEFAULT 'PENDIENTE',
    "Origen" VARCHAR(20) NOT NULL DEFAULT 'movil',
    "CreadoEn" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "IX_Pendientes_Estado" ON "Pendientes"("Estado");
CREATE INDEX IF NOT EXISTS "IX_Pendientes_FechaISO" ON "Pendientes"("FechaISO");

-- ITEMS DE PENDIENTES
CREATE TABLE IF NOT EXISTS "ItemsPendiente" (
    "Id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "PendienteId" BIGINT NOT NULL,
    "Nombre" VARCHAR(200) NOT NULL,
    "Cantidad" INT NOT NULL,
    "Precio" NUMERIC(18,2) NOT NULL,
    CONSTRAINT "FK_ItemsPendiente_Pendientes" FOREIGN KEY ("PendienteId") REFERENCES "Pendientes"("Id") ON DELETE CASCADE
);

-- CIERRES DE TURNO
CREATE TABLE IF NOT EXISTS "Cierres" (
    "Id" BIGINT PRIMARY KEY,
    "Secretario" VARCHAR(100) NOT NULL,
    "Turno" VARCHAR(20) NOT NULL,
    "FechaCierre" VARCHAR(20) NOT NULL,
    "HoraCierre" VARCHAR(20) NOT NULL,
    "CantidadVentas" INT NOT NULL DEFAULT 0,
    "TotalGeneral" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "TotalEfectivo" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "TotalQR" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "TotalMixtoEfectivo" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "TotalMixtoQR" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "TotalAnticipos" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "TotalDescuentos" NUMERIC(18,2) NOT NULL DEFAULT 0,
    "Sucursal" VARCHAR(100) NULL,
    "CreadoEn" TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS "IX_Cierres_Secretario" ON "Cierres"("Secretario");
CREATE INDEX IF NOT EXISTS "IX_Cierres_FechaCierre" ON "Cierres"("FechaCierre");

-- CONFIGURACIÓN SUCURSALES
CREATE TABLE IF NOT EXISTS "ConfigSucursales" (
    "Id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Sucursal" VARCHAR(100) NOT NULL UNIQUE,
    "Consulta" BOOLEAN NOT NULL DEFAULT TRUE,
    "Rapido" BOOLEAN NOT NULL DEFAULT TRUE
);
